### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by xiaoshumiao6** [zouzanyan/douyin_crawl#5]
https://www.iesdouyin.com/aweme/v1/web/aweme/detail/?aweme_id=7261524574834134272&aid=1128&version_name=23.5.0&device_platform=android&os_version=2333

这个方案，现在不支持了

**Comment by zouzanyan** [comment]
你好,单视频爬取确实已经失效,暂时没有维护

**Comment by xiaoshumiao6** [comment]
您好： 
尝试进行多个下载， cookie 会碰到限速： ratelimit triggered；
大佬有解决方案吗？

**Comment by zouzanyan** [comment]
你好,目前尚不清楚触发ratelimit triggered的具体原因,目前正在解决中

**Comment by zouzanyan** [comment]
已修复
